---
title: "CanonicalStartSites"
author: "Hannah Serio"
date: "2025-05-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tibble)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(openxlsx)
```

## processing all files prior to plotting
```{r file formatting}
# HELA
nmHELA <- read.table("/Volumes/fsmresfiles/Basic_Sciences/Pharm/Arango_Lab/Quest/2ometh/canonicalStartSites/nmseq/HeLaCanonicalStartNm.bed", header = FALSE, sep = "\t", stringsAsFactors = FALSE)
nmmtHELA <- read.table("/Volumes/fsmresfiles/Basic_Sciences/Pharm/Arango_Lab/Quest/2ometh/canonicalStartSites/nmmtseq/HeLaCanonicalStartNm.bed", header = FALSE, sep = "\t", stringsAsFactors = FALSE)
njuHELA <- read.table("/Volumes/fsmresfiles/Basic_Sciences/Pharm/Arango_Lab/Quest/2ometh/canonicalStartSites/nju/HeLaCanonicalStartNm.bed", header = FALSE, sep = "\t", stringsAsFactors = FALSE)
mlmHELA <- read.table("/Volumes/fsmresfiles/Basic_Sciences/Pharm/Arango_Lab/Quest/2ometh/canonicalStartSites/mlm/HeLaCanonicalStart0basedNm.bed", header = FALSE, sep = "\t", stringsAsFactors = FALSE)

# HEK
nmHEK <- read.table("/Volumes/fsmresfiles/Basic_Sciences/Pharm/Arango_Lab/Quest/2ometh/canonicalStartSites/nmseq/HEKCanonicalStartNm.bed", header = FALSE, sep = "\t", stringsAsFactors = FALSE)
njuHEK <- read.table("/Volumes/fsmresfiles/Basic_Sciences/Pharm/Arango_Lab/Quest/2ometh/canonicalStartSites/nju/HEKCanonicalStartNm.bed", header = FALSE, sep = "\t", stringsAsFactors = FALSE)
mlmHEK <- read.table("/Volumes/fsmresfiles/Basic_Sciences/Pharm/Arango_Lab/Quest/2ometh/canonicalStartSites/mlm/HEKCanonicalStart0basedNm.bed", header = FALSE, sep = "\t", stringsAsFactors = FALSE)

# HepG2
nmmtHEPG2 <- read.table("/Volumes/fsmresfiles/Basic_Sciences/Pharm/Arango_Lab/Quest/2ometh/canonicalStartSites/nmmtseq/HepG2CanonicalStartNm.bed", header = FALSE, sep = "\t", stringsAsFactors = FALSE)
mlmHEPG2 <- read.table("/Volumes/fsmresfiles/Basic_Sciences/Pharm/Arango_Lab/Quest/2ometh/canonicalStartSites/mlm/HepG2CanonicalStart0basedNm.bed", header = FALSE, sep = "\t", stringsAsFactors = FALSE)

# A549
njuA549 <- read.table("/Volumes/fsmresfiles/Basic_Sciences/Pharm/Arango_Lab/Quest/2ometh/canonicalStartSites/nju/A549CanonicalStartNm.bed", header = FALSE, sep = "\t", stringsAsFactors = FALSE)

data_list <- list(
  nmHELA = nmHELA,
  nmmtHELA = nmmtHELA,
  njuHELA = njuHELA,
  mlmHELA = mlmHELA,
  nmHEK = nmHEK,
  njuHEK = njuHEK,
  mlmHEK = mlmHEK,
  nmmtHEPG2 = nmmtHEPG2,
  mlmHEPG2 = mlmHEPG2,
  njuA549 = njuA549
)

```

## Dot Plot Studies Combined

```{r CanonicalNmCellLine, fig.width=7, fig.height=6, fig.path='R_plots/', dev=c('png', 'pdf')}

# Set the allowed positions explicitly, excluding 0
codon_levels <- factor(c(-3, -2, -1, 1, 2, 3, 4), levels = c(-3, -2, -1, 1, 2, 3, 4))

freq_list <- lapply(names(data_list), function(name) {
  df <- data_list[[name]]
  last_col <- df[[ncol(df)]]
  counts <- as.data.frame(table(factor(last_col, levels = levels(codon_levels))))
  colnames(counts) <- c("position", "Freq")
  counts$Prefix <- str_extract(name, "^[a-z]+")
  counts$CellLine <- str_extract(name, "HELA|HEK|HEPG2|A549")
  counts
})

combined_data <- bind_rows(freq_list)

collapsed_data <- combined_data %>%
  group_by(position, CellLine) %>%
  summarize(Freq = sum(Freq), .groups = "drop")

collapsed_data$position <- factor(collapsed_data$position, levels = as.character(c(-3, -2, -1, 1, 2, 3, 4)))
collapsed_data$CellLine <- factor(collapsed_data$CellLine, levels = c("HELA", "HEK", "HEPG2", "A549"))

ggplot(collapsed_data, aes(x = position, y = Freq, color = CellLine, group = CellLine)) +
  geom_point(size = 3) +
  scale_x_discrete(
        drop = FALSE,
        labels = c(
        "-3" = "-3",
        "-2" = "-2",
        "-1" = "-1",
        "1" = "+1",
        "2" = "+2",
        "3" = "+3",
        "4" = "+4"
  )) +
  scale_y_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0.05))) +
  labs(
    title = paste("2'O-me Frequency in Canonical Start Codon by Cell Line"),
    x = "Position Relative to Start Codon",
    y = "# of sites",
    color = NULL  # No title for legend, or change to "Dataset" if preferred
  ) +
  scale_color_manual(
    values = c(
      "HELA" = "#d62728",   # blue
      "HEK" = "skyblue2",    # orange
      "HEPG2" = "khaki2",  # green
      "A549" = "tan1"    # red
    ),
    labels = c(
      "HELA" = "HeLa",
      "HEK" = "HEK293T",
      "HEPG2" = "HepG2",
      "A549" = "A549"
    ),
    name = "Cell Line"  # legend title
  ) +
  theme_minimal(base_size = 14) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks = element_line(color = "black"),
    axis.ticks.length = unit(5, "pt"),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    plot.title = element_text(size = 16, face = "bold"),
    axis.line.y = element_line(color = "black"),
    axis.line.x = element_line(color = "black"),
    legend.text = element_text(size = 12)
  )

```